### ISSUE TITLE
Change channel bug.

### ISSUE THREAD

**Issue by MageNuada** [TwitchLib/TwitchLib#1039]
TwitchClient.JoinedChannels doesn't cleared after calling LeaveChannel.

**Comment by swiftyspiffy** [comment]
So, this is sort of by design. The JoinedChannels is only updated when it receives confirming from Twitch via `PART` message: https://github.com/TwitchLib/TwitchLib.Client/blob/master/TwitchLib.Client/TwitchClient.cs#L1211

Sources from: https://github.com/TwitchLib/TwitchLib.Client/blob/master/TwitchLib.Client/TwitchClient.cs#L1030

**Comment by MageNuada** [comment]
So there is problems with twitch?

Also event OnLeftChannel doesn't fire.

**Comment by Syzuna** [comment]
If OnUserLeft is triggered instead of OnLeftChannel it would indicate that you didnt provide the Client with the correct bot username to determine if its the bot parting a channel or a user leaving the channel.

**Comment by MageNuada** [comment]
Thx, Syzuna, i've fixed name, and all is working now.
