### ISSUE TITLE
TwitchClient.BanUser, TwitchClient.TimeoutUser don't work

### ISSUE THREAD

**Issue by peerware** [TwitchLib/TwitchLib#1137]
![image](https://github.com/TwitchLib/TwitchLib/assets/99911701/161c40ff-fd13-4f09-8711-c08b7b053c59)
I remember this used to work but now it doesn't, trying to think of a good way to work around this
I'm using TwitchLib 3.5.3 with .Net 6.0

I tested this by using breakpoints and intentionally triggering my spam filter from an alt account on a different laptop, verified that the bot is moderator and the alt is a regular user

**Comment by Hampo** [comment]
Hi @conneteched,

This is due to a change Twitch announced in 2022, and started implementing in 2024: https://discuss.dev.twitch.tv/t/deprecation-of-chat-commands-through-irc/40486

To summarise, IRC Clients (which is all `TwitchLib.Client` really is) no longer have access to the majority of slash commands. You can take a look at the [Migration Guide](https://dev.twitch.tv/docs/irc/chat-commands/#migration-guide) to see what slash command became what API endpoint, then use [`TwitchLib.Api`](https://github.com/TwitchLib/TwitchLib.Api/) to call them.

As a side note, I would recommend not using the group NuGet package, and instead install the previews of the individual packages. Every individual package is currently undergoing massive internal changes, so changes haven't been pushed to stable yet, but all new/updated Twitch features are in the dev builds. The (current) latest versions are:
- `TwitchLib.Client` - `4.0.0-preview-5677f50eb2a7544e1b9b136a0e1537abf5083385`
- `TwitchLib.Api` - `3.10.0-preview-9ccfdfb`

Thanks,
Josh / Proddy

**Comment by conneteched** [comment]
Appreciate the comprehensive explanation, thank you
