### ISSUE TITLE
FollowerService only accepts 1 client

### ISSUE THREAD

**Issue by D3adL0ck** [TwitchLib/TwitchLib#304]
Hey so currently the FollowerService only allows 1 client to be used per instance.
Would be awesome if multiple clients could be used in only 1 instance.

**Comment by swiftyspiffy** [comment]
Hey, thanks for creating an issue. Currently debating if it's better design to just create multiple follower service objects, or to have a single follower service object. The reason is because there are a number of instance variables in follower service that the customer may want to differentiate between services (cache, interval, etc). Thoughts?

**Comment by D3adL0ck** [comment]
I think that it should be a single FollowerService object with like optional parameters in a ListenToChannel method so that each channel entry could have its own requirements, and like store them as a dictionary of channel name and last followers response (optionally: alongside a DateTime object to know when the last update occurred).

**Comment by swiftyspiffy** [comment]
Ya, you're probably right, I think. Will think it over for a little bit longer though.

**Comment by LuckyNoS7evin** [comment]
I think this is a good idea, I've been looking as the "how best to do this" and I have an idea. I may do this after finishing the Extension stuff. Unless anyone else gets there first

**Comment by swiftyspiffy** [comment]
I haven't had a ton of time recently to get it done, but it's been on my radar. If you want to do it though, go for it!

**Comment by swiftyspiffy** [comment]
This issue was moved to TwitchLib/TwitchLib.Api#35
