### ISSUE TITLE
Running UpdateChannelAsync results in BadRequestException

### ISSUE THREAD

**Issue by Itsmadhatter** [TwitchLib/TwitchLib#383]
When i run this line:
`await _api.Channels.v5.UpdateChannelAsync(_user.Id, title);`

it throws an BadRequestException.

The Response Message from Twitch is:
"Must provide a valid Content-Type header with a request body. Please use application/json or application/x-www-form-urlencoded"

In the Request Header is the property Content-Type twice
the valid property "Content-Type" is "text/plain" and the other property "ContentType" is "application/json" thats why Twitch response with that message.

![screenshot](https://user-images.githubusercontent.com/4571029/38252253-f0a50040-3753-11e8-9e1b-d34eedfae0aa.png)

**Comment by Mahsaap** [comment]
"Headers for the post/put not being set correctly during the http calls" from Syzuna
He's going look into it later. Just wanted to give you a heads up.

**Comment by Syzuna** [comment]
ok so that is strange tbh. I know swifty overwrote some changes I made to the older code while adding the bits api but I cant see anything causing this. the request content type is set to application/json.
Also strange that the content type header with the correct value has the wrong name ContentType instead of Content-Type

**Comment by swiftyspiffy** [comment]
@Itsmadhatter Check 08eae9bb86347f084366e214ab95ab9ebfd629fe

It should fix your problem. I tested UpdateChannelAsync and it appears to work after.

**Comment by Itsmadhatter** [comment]
It´s works now. Thanks for the quick fix :D
