### ISSUE TITLE
Client OnDisconnected event not reliably firing

### ISSUE THREAD

**Issue by kimimaru4000** [TwitchLib/TwitchLib#474]
Environment:
```
- TwitchLib 3.1.0 NuGet
  - TwitchLib.Api 3.1.2
  - TwitchLib.Client 3.1.4
  - TwitchLib.PubSub 3.1.3 
- .NET Core 2.1 application written in C#
```
The `TwitchClient.OnDisconnected` event does not fire reliably, and I'm not sure how to get it to fire. If I disconnect my internet while my bot is running, I don't get this event even after a minute or two. When I reconnect to the internet, everything else in my bot is broken and no more events are fired until I completely restart the application. Sometimes when I leave it idle for long periods of time, I'll see the disconnection event despite being connected to the internet.

[Here's the code that tells me when it's fired](https://github.com/teamradish/TRTwitchPlaysBot/blob/master/TRBot/TRBotCore/Classes/BotProgram.cs#L513). As previously mentioned, I do not see this message when I intentionally disconnect from the internet. All the message events work flawlessly, and I haven't had any issues with them. Am I handling things right?

**Comment by vaindil** [comment]
I'm having a similar problem, or at least I think this is the same problem I'm having. My bots randomly disconnect from chat, sometimes the event fires and sometimes it doesn't.

**Comment by swiftyspiffy** [comment]
OnDisconnected fires from a communications event, which itself can sometimes take a few seconds to notice a disconnect. In the current design, there's not much we can do about this, but in the rewrite thats in progress, I believe this has been fixed. I would be interested to know if the random disconnects have been fixed in recent updates. Feel free to reopen if needed.
