### ISSUE TITLE
Add ability to use custom chat servers

### ISSUE THREAD

**Issue by kingbri1** [TwitchLib/TwitchLib#493]
I was recently informed of a website called [fdgt](https://fdgt.dev/).

This allows bot developers such as myself to trigger events from twitch such as subs, bits, and gifted subs without paying money. However, using this service requires me to specify a custom server url to connect to on bot startup.

**Comment by trezy** [comment]
Hey @bdashore3, I'm the creator of [`fdgt`](https://fdgt.dev). My understanding is that it's currently not possible to connect to `fdgt` with TwitchLib because the `ConnectionCredentials` model exposes a _getter_ for `TwitchWebsocketURI`, but not a _setter_. Hopefully, this is something that'll change soon, but right now it's just not possible.

https://github.com/TwitchLib/TwitchLib.Client/blob/e0a60e62272ef29744793fd7d9bcd0df87acf4b4/TwitchLib.Client.Models/ConnectionCredentials.cs#L12

**Comment by prom3theu5** [comment]
Hey there

The constructor for ConnectionCredentials actually has a third optional parameter for the Web Socket Uri as a string.
twitchWebsocketURI.
That said - That's not actually used for connection anymore

The problem lies in the TwitchLib.Communication package.
I (or someone else - I've not been around in a long time) really need to revisit it.
Take a look at: [WebSocketClient.cs](https://github.com/TwitchLib/TwitchLib.Communication/blob/master/src/TwitchLib.Communication/Clients/WebsocketClient.cs)
The issue is the connection URL is hardcoded.
It should really be a property of the ClientOptions object.

You could technically take a copy of that file, and change the URL - then pass it through to creation of a TwitchClient, as long as you fully implement the IClient interface.

Say you copied the class to a class called **CustomTwitchClient** with the URL changed
Your twitch initililization would be as follows:

```csharp
var credentials = new ConnectionCredentials("twitch_username", "access_token");
var clientOptions = new ClientOptions
{
    MessagesAllowedInPeriod = 750,
    ThrottlingPeriod = TimeSpan.FromSeconds(30)
};
var customClient = new CustomTwitchClient(clientOptions);
var client = new TwitchClient(customClient);
var client.Initialize(credentials, "channel");
```

**Comment by itssimple** [comment]
I can take a look at it, if PRs are welcome, currently I use a hacky solution to change the URL and thought I would share it with anyone who wants to try it out right now.

I used reflection to grab the IClient (in this case the WebSocketClient), and then from there grabbed the field for the Url, and set the value with reflection as well.

It's an ugly hack, but it works if you wanna get going with [fdgt](https://fdgt.dev) right now. :)

https://gist.github.com/itssimple/d5afe8a21ddfe52772e07f8dc0b9d433

**Comment by swiftyspiffy** [comment]
I think for the time being, following the model that @itssimple did is probably the correct way until the rewrite is completed. The rewrite should have good support for this.
